---

- hosts: all
  roles:
    - bootstrap_machines
    - update_host
    - install_prerequisites
    - checkout_repos
    - configure_network

- hosts: tf_controller
  roles:
    - setup_ssh_keys
    - install_docker
    - install_ansible

