---

- hosts: all
  remote_user: centos
  roles:
    - bootstrap_machines
    - update_host
    - install_prerequisites
    - checkout_repos
    - configure_network

- hosts: tf_controller
  remote_user: centos
  roles:
    - setup_ssh_keys

