---

- name: create /etc/docker directory if not exists
  file:
    path: '/etc/docker'
    state: directory
    owner: root
    group: root
    mode: 0600
  become: true

- name: configure docker daemon.json
  template:
    src: 'daemon.j2'
    dest: '/etc/docker/daemon.json'
    owner: root
    group: root
    mode: 0400
  notify: docker-service
  become: true
