---

- include_tasks: 'install_docker_{{ ansible_distribution | lower }}.yaml'
  when: install_docker

- name: add remote user to docker group
  user:
    name: '{{ remote_user }}'
    groups: 'docker'
    append: yes
  become: true

- name: run Docker service on target host
  meta: flush_handlers
