---

- name: change default Docker network
  blockinfile:
    block: |
      {
         "bip": "172.22.0.1/16"
      }
    marker: false
    path: '/etc/docker/daemon.json'
    owner: root
    group: root
    mode: 0644
    create: yes
  notify: docker-service
  when: configure_docker_network
  become: true

- include_tasks: 'install_docker_{{ ansible_distribution | lower }}.yaml'
  when: install_docker

- name: add remote user to docker group
  user:
    name: '{{ remote_user }}'
    groups: 'docker'
    append: yes
  become: true

- name: run Docker service on target host
  meta: flush_handlers
