---

- name: install yum-utils
  package:
    name: yum-utils
    state: present
  become: true

- name: update CentOS machine
  yum:
    name: '*'
    state: latest
  become: true
  tags:
    - skip_ansible_lint

- name: check if reboot is required
  shell: 'needs-restarting -r'
  failed_when: false
  changed_when: false
  register: reboot_hint

- debug:
    msg: 'trigger machine reboot'
  changed_when: true
  notify: reboot-machine
  when: reboot_hint.rc != 0

- name: reboot machine if needed
  meta: flush_handlers

