---

- when:
    - ansible_distribution | lower == 'debian'
  become: true
  block:
    - name: update ubuntu machine
      apt:
        update_cache: yes
        cached_valid_time: 3600

    - name: upgrade installed packages
      apt:
        name: '*'
        state: latest
      tags:
        - skip_ansible_lint

- name: update centos machine
  yum:
    name: '*'
    state: latest
  when:
    - ansible_distribution | lower == 'redhat'
  become: true
  tags:
    - skip_ansible_lint

