---

- name: upgrade pip & setuptools to newest version (devstack doesn't handle this properly)
  pip:
    name: ['pip', 'setuptools']
    state: latest
  become: true
  tags:
    - skip_ansible_lint

- name: deploy OpenStack environment with stack.sh (might take a longer while)
  shell: './stack.sh'
  args:
    chdir: '{{ ansible_env.HOME }}/devstack'
    executable: '/bin/bash'
  ignore_errors: yes
  register: stack_sh
  tags:
    - skip_ansible_lint

- name: check status of deployment script
  file:
    path: '/tmp/discover_hosts'
    state: touch
    owner: centos
    group: root
    mode: 0644
  when: stack_sh.rc == 0
  become: true

