---

- name: include distribution specific package names
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution | lower }}.yaml'
        - 'os_default.yaml'
      paths:
        - '../vars'
  changed_when: true

- name: install prerequisities
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - '{{ packages_name }}'
  become: true

