---

- name: read remote public user key
  command: 'cat {{ ansible_env.HOME }}/.ssh/id_rsa.pub'
  register: user_key_content
  tags:
    - skip_ansible_lint

- name: read root public user key
  command: 'cat /root/.ssh/id_rsa.pub'
  register: root_key_content
  become: true
  tags:
    - skip_ansible_lint

- name: make sure ssh keys are present in authorized_keys
  authorized_key:
    user: 'root'
    key: '{{ item }}'
    state: present
    exclusive: no
  with_items:
    - '{{ user_key_content.stdout }}'
    - '{{ root_key_content.stdout }}'
  become: true

