---

- name: include os specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution | lower }}.yaml'
        - 'os_default.yaml'
      paths:
        - '../vars'

- name: copy interface config template
  template:
    src: 'ifcfg-{{ ansible_distribution | lower }}.j2'
    dest: '{{ intf_config_path }}/{{ intf_script }}'
  notify:
    - enable-interface
  become: true

- meta: reconfigure {{ backend_interface }} interface
  flush: flush_handlers

