---

devstack_dest: '/opt/stack'
devstack_logfile: '{{ devstack_dest}}/logs/stack.sh.log'
devstack_admin_passwd: 'admin'
devstack_git_base: 'https://git.openstack.org'
devstack_branch: 'master'
devstack_multihost: true
devstack_dvr: true
devstack_systemd: true
devstack_venv: false
devstack_service_ip: "{%set hostname = groups['os_controller'][0] %}{{ hostvars[hostname]['ansible_default_ipv4']['address'] }}"
devstack_controller_fip: "{%set hostname = groups['os_controller'][0] %}{{ hostvars[hostname].ansible_host }}"
opencontrail_api_ip: "{%set hostname = groups['tf_controller'][0] %}{{ hostvars[hostname]['ansible_default_ipv4']['address'] }}"
opencontrail_api_port: '8082'

