---

- when: restack
  block:
    - name: get status of target running services
      service_facts:

    - name: initialize devstack services list
      set_fact:
        devstack_running: []

    - name: check status of devstack services
      set_fact:
        devstack_running: '{{ devstack_running + [item] }}'
      when: >
        hostvars[inventory_hostname]['services']['{{ item }}']['state'] == 'running' and
        hostvars[inventory_hostname]['services']['{{ item }}']['name'] == 'devstack@*'
      with_items: "{{ hostvars[inventory_hostname]['services'].keys() }}"

- name: unstack current environment
  shell: ./unstack.sh
  args:
    chdir: '{{ ansible_env.HOME }}/devstack'
  ignore_errors: yes
  when: devstack_running

- name: run OpenStack environment with stack.sh
  command: ./stack.sh
  args:
    chdir: '{{ ansible_env.HOME }}/devstack'

